import React,{useEffect,useRef,useState} from 'react';
import {Search,Plus,X,Settings,Bookmark,ArrowUpRight,Copy,Download,Scissors,Image,FolderOpen,Command,LoaderCircle,Check,Minus} from 'lucide-react';
import {removeImageBackground} from './background';
const bridge=window.scout;
const fresh=()=>({id:crypto.randomUUID(),draft:'',query:'',results:[],loading:false,error:'',generation:0});
const errorText=e=>String(e?.message||e).replace(/^Error invoking remote method '[^']+':\s*(Error:\s*)?/,'').replace(/^Error:\s*/,'');
export default function App(){
 const [tabs,setTabs]=useState(()=>[fresh()]),[active,setActive]=useState(null),[settings,setSettings]=useState(null),[saved,setSaved]=useState([]),[filter,setFilter]=useState(''),[showSettings,setShowSettings]=useState(false),[notice,setNotice]=useState(''),[preview,setPreview]=useState(null),[busy,setBusy]=useState({});
 const input=useRef(null),noticeTimer=useRef(),tabsRef=useRef(tabs);tabsRef.current=tabs;
 const selected=active||tabs[0]?.id,current=tabs.find(t=>t.id===selected),isSaved=selected==='saved';
 const notify=message=>{setNotice(message);clearTimeout(noticeTimer.current);noticeTimer.current=setTimeout(()=>setNotice(''),6500);};
 useEffect(()=>{if(!bridge){notify('Open Image Scout from the desktop app to connect to image search.');return;}bridge.settings().then(setSettings).catch(e=>notify(errorText(e)));bridge.library().then(setSaved).catch(e=>notify(errorText(e)));return bridge.onFocus(()=>input.current?.focus());},[]);
 const newTab=()=>{const tab=fresh();setTabs(t=>[...t,tab]);setActive(tab.id);setTimeout(()=>input.current?.focus(),0);};
 const closeTab=id=>{const remaining=tabsRef.current.filter(t=>t.id!==id);if(!remaining.length)remaining.push(fresh());setTabs(remaining);if(selected===id)setActive(remaining.at(-1).id);};
 useEffect(()=>{const handler=e=>{if(e.key==='Escape'){if(preview)setPreview(null);else if(showSettings)setShowSettings(false);else bridge?.hide();return;}if(preview||showSettings){if(e.key==='Tab'){const nodes=[...document.querySelectorAll('[role="dialog"] button:not(:disabled),[role="dialog"] input')];const first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}if((e.ctrlKey||e.metaKey)&&['t','w','l'].includes(e.key.toLowerCase()))e.preventDefault();return;}if((e.ctrlKey||e.metaKey)&&!e.altKey){if(e.key.toLowerCase()==='t'){e.preventDefault();newTab();}if(e.key.toLowerCase()==='w'){e.preventDefault();if(!isSaved)closeTab(selected);}if(e.key.toLowerCase()==='l'){e.preventDefault();input.current?.focus();input.current?.select();}}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler);});
 useEffect(()=>{input.current?.focus();},[selected]);
 useEffect(()=>()=>{clearTimeout(noticeTimer.current);},[]);
 useEffect(()=>()=>{if(preview?.objectUrl)URL.revokeObjectURL(preview.objectUrl);},[preview]);
 const update=(id,change)=>setTabs(all=>all.map(t=>t.id===id?{...t,...change}:t));
 async function search(value){if(!current)return;const query=(value??current.draft).trim();if(!query)return;if(!settings?.hasKey){setShowSettings(true);return;}const id=current.id,generation=current.generation+1;update(id,{draft:query,query,generation,loading:true,error:'',results:[]});try{const results=await bridge.search(query,id);setTabs(all=>all.map(t=>t.id===id&&t.generation===generation?{...t,results,loading:false}:t));}catch(e){setTabs(all=>all.map(t=>t.id===id&&t.generation===generation?{...t,error:errorText(e),loading:false}:t));}}
 async function action(item,query,copy,cutout){const key=item.id;setBusy(b=>({...b,[key]:copy?'Copying…':'Saving…'}));try{const payload={query,title:item.title,copy};if(cutout)payload.png=new Uint8Array(await cutout.arrayBuffer());else if(item.path)payload.savedId=item.id;else payload.url=item.url;const result=await bridge.save(payload);setSaved(all=>[result.record,...all.filter(x=>x.id!==result.record.id)]);notify(result.warning||(copy?'Copied to clipboard · Saved in Downloads':'Saved in Downloads'));}catch(e){notify(errorText(e));}finally{setBusy(b=>({...b,[key]:null}));}}
 async function cutout(item,query){setBusy(b=>({...b,[item.id]:'Preparing model…'}));try{const bytes=await bridge.imageBytes(item.url);const blob=await removeImageBackground(bytes,p=>setBusy(b=>({...b,[item.id]:p})));setPreview({item,query,blob,objectUrl:URL.createObjectURL(blob)});}catch(e){notify(errorText(e));}finally{setBusy(b=>({...b,[item.id]:null}));}}
 const visible=isSaved?saved.filter(x=>`${x.query} ${x.title}`.toLowerCase().includes(filter.toLowerCase())):current?.results||[];
 function card(item){const query=isSaved?item.query:current.query;return <article className="image-card" key={item.id}><button className="image-open" aria-label={`Preview ${item.title}`} onClick={()=>setPreview({item,query})}>{item.preview||item.thumbnail?<img src={item.preview||item.thumbnail} alt={item.title} loading="lazy" onError={e=>{e.currentTarget.style.opacity='.15';}}/>:<Image size={40}/>}</button><div className="card-shade"/><div className="card-info"><span>{item.title}</span><small>{item.source||item.query||'Google Images'}</small></div><div className="card-actions"><button disabled={!!busy[item.id]} aria-label={`Copy ${item.title}`} title="Copy & save" onClick={()=>action(item,query,true)}><Copy size={15}/></button><button disabled={!!busy[item.id]} aria-label={`Save ${item.title}`} title={item.path?'Show in Downloads':'Save to Downloads'} onClick={()=>item.path?bridge.reveal(item.id).catch(e=>notify(errorText(e))):action(item,query,false)}>{item.path?<FolderOpen size={15}/>:<Download size={15}/>}</button>{!item.path&&<button disabled={!!busy[item.id]} aria-label={`Remove background ${item.title}`} title="Remove background" onClick={()=>cutout(item,query)}><Scissors size={15}/></button>}</div>{busy[item.id]&&<div className="card-busy"><LoaderCircle className="spin" size={18}/><span>{busy[item.id]}</span></div>}</article>;}
 return <div className="app-shell"><header className="titlebar"><div className="brand"><span className="brand-mark"><Command size={16}/></span> scout<span className="brand-dot">.</span></div><span className="titlebar-caption">A little window. Endless inspiration.</span><div className="window-actions"><button aria-label="Settings" title="Settings" onClick={()=>setShowSettings(true)}><Settings size={16}/></button><button aria-label="Hide window" title="Hide · Esc" onClick={()=>bridge?.hide()}><Minus size={18}/></button></div></header>
 <nav className="tabbar" aria-label="Search tabs"><div className="search-tabs" role="tablist">{tabs.map(tab=><div className={`tab ${selected===tab.id?'active':''}`} key={tab.id}><button role="tab" aria-selected={selected===tab.id} onClick={()=>setActive(tab.id)}>{tab.loading?<LoaderCircle size={13} className="spin"/>:<Search size={13}/>}<span>{tab.query||'New search'}</span></button><button className="tab-close" aria-label={`Close ${tab.query||'search'} tab`} onClick={()=>closeTab(tab.id)}><X size={12}/></button></div>)}</div><button className="new-tab" aria-label="New tab" title="New tab · Ctrl+T" onClick={newTab}><Plus size={16}/></button><button className={`saved-tab ${isSaved?'active':''}`} role="tab" aria-selected={isSaved} onClick={()=>setActive('saved')}><Bookmark size={14}/>Saved<span>{saved.length}</span></button></nav>
 <main><form className="search-form" onSubmit={e=>{e.preventDefault();if(!isSaved)search();}}><Search size={22}/><input ref={input} aria-label={isSaved?'Filter saved images':'Search images'} placeholder={isSaved?'Find something you saved…':'Search Google Images…'} value={isSaved?filter:current?.draft||''} onChange={e=>isSaved?setFilter(e.target.value):update(current.id,{draft:e.target.value})}/>{!isSaved&&<button className="search-submit" title="Search" type="submit"><span>Search</span><kbd>↵</kbd></button>}</form>
 <div className="section-meta"><span>{isSaved?'YOUR COLLECTION':current?.query?`RESULTS FOR “${current.query}”`:'YOUR NEXT IDEA STARTS HERE'}</span><span>{isSaved?`${visible.length} saved`:current?.loading?'Searching Google Images…':current?.query?`${visible.length} images`:'Google Images'}<span className="tiny-dot"/></span></div>
 {current?.error&&!isSaved?<div className="empty"><Search size={30}/><h1>Search hit a snag.</h1><p>{current.error}</p><button className="primary" onClick={()=>search()}>Try again</button></div>:current?.loading&&!isSaved?<div className="image-grid skeleton-grid">{Array.from({length:9},(_,i)=><div className="skeleton" key={i}/>)}</div>:visible.length?<div className="image-grid">{visible.map(card)}</div>:<div className="empty"><div className="empty-art"><div/><div/><div><Image size={30}/></div><span>✦</span></div><span className="eyebrow">{isSaved?'KEEP THE GOOD ONES':'LESS SEARCHING. MORE MAKING.'}</span><h1>{isSaved?'Your finds live here.':current?.query?'Nothing here. Yet.':'Find it. Grab it. Make it.'}</h1><p>{isSaved?'Every image you copy or save lands here, and in Downloads.':current?.query?'Try a different phrase to find the right image.':'Images for your next big idea, one quick search away.\nOpen a few tabs. Follow your curiosity.'}</p>{!isSaved&&!current?.query&&<div className="suggestions">{['Brutalist architecture','Botanical textures','Monkeys'].map(q=><button key={q} onClick={()=>search(q)}>{q}<ArrowUpRight size={13}/></button>)}</div>}{!isSaved&&settings&&!settings.hasKey&&<button className="connect-key" onClick={()=>setShowSettings(true)}>Connect your SerpApi key <ArrowUpRight size={13}/></button>}</div>}
 </main><footer><span className="footer-status"><span className="status-light"/>{settings?.hasKey?'Ready when you are':'Connect SerpApi to get started'}</span><div><span><kbd>Ctrl T</kbd> New tab</span><span><kbd>Esc</kbd> Hide</span></div></footer>
 {notice&&<div className="toast" role="status"><Check size={16}/>{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}><X size={14}/></button></div>}
 {showSettings&&<SettingsPanel settings={settings} close={()=>setShowSettings(false)} onSave={value=>{setSettings(value);notify('Settings saved');}}/>}
 {preview&&<div className="modal-backdrop" onClick={()=>setPreview(null)}><section className="preview-modal" role="dialog" aria-modal="true" aria-label="Image preview" onClick={e=>e.stopPropagation()}><div className="modal-heading"><div><h2>{preview.blob?'Background removed':preview.item.title}</h2><p>{preview.query}{preview.blob?' · Transparent PNG':''}</p></div><button aria-label="Close preview" autoFocus onClick={()=>setPreview(null)}><X size={18}/></button></div><div className="preview-image checker"><img src={preview.objectUrl||preview.item.preview||preview.item.url||preview.item.thumbnail} alt={preview.item.title}/></div><div className="preview-actions"><span>{preview.blob?'Ready for your next design.':'Copy and save in one click.'}</span><button disabled={!!busy[preview.item.id]} onClick={()=>preview.item.path&&!preview.blob?bridge.reveal(preview.item.id).catch(e=>notify(errorText(e))):action(preview.item,preview.query,false,preview.blob)}><Download size={15}/>{preview.item.path&&!preview.blob?'Show in Downloads':'Save'}</button><button className="primary" disabled={!!busy[preview.item.id]} onClick={()=>action(preview.item,preview.query,true,preview.blob)}><Copy size={15}/>Copy image</button></div></section></div>}
 </div>;
}
function SettingsPanel({settings,close,onSave}){const [key,setKey]=useState(''),[shortcut,setShortcut]=useState(settings?.shortcut||'Alt+Space'),[error,setError]=useState(''),[saving,setSaving]=useState(false);async function submit(e){e.preventDefault();setSaving(true);setError('');try{const result=await bridge.configure({...key.trim()?{apiKey:key.trim()}:{},shortcut});setKey('');onSave(result);close();}catch(e){setError(errorText(e));}finally{setSaving(false);}}return <div className="modal-backdrop" onClick={close}><section className="settings-modal" role="dialog" aria-modal="true" aria-label="Settings" onClick={e=>e.stopPropagation()}><div className="modal-heading"><div><span className="eyebrow">MAKE YOURSELF AT HOME</span><h2>Settings</h2></div><button aria-label="Close settings" onClick={close}><X size={18}/></button></div><form onSubmit={submit}><label htmlFor="api-key">SerpApi key <span className="key-badge">{settings?.hasKey?'Connected':'Not connected'}</span></label><input id="api-key" autoFocus type="password" autoComplete="off" spellCheck="false" placeholder={settings?.hasKey?'Enter a new key to replace existing':'Paste your private API key'} value={key} onChange={e=>setKey(e.target.value)}/><p>Encrypted on this computer. Searches run only when you press Enter.</p><label htmlFor="shortcut">Global shortcut</label><input id="shortcut" value={shortcut} onChange={e=>setShortcut(e.target.value)} placeholder="Alt+Space"/><p>For example: Alt+Space or Control+Alt+Space.</p>{settings?.shortcutWarning&&<p className="form-error">{settings.shortcutWarning}</p>}<label>Save location</label><div className="path"><FolderOpen size={15}/>{settings?.downloads||'Your Downloads folder'}</div><p>Copied images are saved here too, with numbered filenames.</p>{error&&<p className="form-error" role="alert">{error}</p>}<div className="settings-footer"><button type="button" onClick={close}>Cancel</button><button className="primary" disabled={saving} type="submit">{saving?'Saving…':'Save settings'}</button></div></form></section></div>}
